export const payments = [
  {
    paymentId: "pay_123456",
    customerEmail: "customer1@example.com",
    paymentMethod: "Credit Card",
    amount: 15000,
    currency: "USD",
    status: "Completed",
    paymentDate: "2024-09-14T12:00:00Z",
    products: [
      {
        productId: "prod_001",
        productName: "Product A",
        quantity: 2,
        unitPrice: 5000,
        totalPrice: 10000,
      },
      {
        productId: "prod_002",
        productName: "Product B",
        quantity: 1,
        unitPrice: 5000,
        totalPrice: 5000,
      },
    ],
    invoiceId: "inv_654321",
    transactionId: "txn_ABC123",
    description: "Purchase of multiple products",
    taxAmount: 1200,
    discountAmount: 500,
    billingAddress: {
      street: "123 Main St",
      city: "New York",
      state: "NY",
      postalCode: "10001",
      country: "USA",
    },
  },
  {
    paymentId: "pay_789012",
    customerEmail: "customer2@example.com",
    paymentMethod: "PayPal",
    amount: 20000,
    currency: "EUR",
    status: "Pending",
    paymentDate: "2024-09-15T10:00:00Z",
    products: [
      {
        productId: "prod_003",
        productName: "Product C",
        quantity: 1,
        unitPrice: 20000,
        totalPrice: 20000,
      },
    ],
    invoiceId: "inv_789012",
    transactionId: "txn_DEF456",
    description: "Purchase of Product C",
    taxAmount: 1800,
    discountAmount: 0,
    billingAddress: {
      street: "456 Park Ave",
      city: "London",
      state: "LN",
      postalCode: "WC2N 5DU",
      country: "UK",
    },
  },
  {
    paymentId: "pay_345678",
    customerEmail: "customer3@example.com",
    paymentMethod: "Bank Transfer",
    amount: 8000,
    currency: "USD",
    status: "Failed",
    paymentDate: "2024-09-13T16:30:00Z",
    products: [
      {
        productId: "prod_004",
        productName: "Product D",
        quantity: 1,
        unitPrice: 8000,
        totalPrice: 8000,
      },
    ],
    invoiceId: "inv_345678",
    transactionId: "txn_GHI789",
    description: "Purchase of Product D",
    taxAmount: 500,
    discountAmount: 300,
    billingAddress: {
      street: "789 King St",
      city: "Toronto",
      state: "ON",
      postalCode: "M5V 1L7",
      country: "Canada",
    },
  },
  {
    paymentId: "pay_901234",
    customerEmail: "customer4@example.com",
    paymentMethod: "Credit Card",
    amount: 30000,
    currency: "USD",
    status: "Completed",
    paymentDate: "2024-09-16T14:15:00Z",
    products: [
      {
        productId: "prod_005",
        productName: "Product E",
        quantity: 3,
        unitPrice: 10000,
        totalPrice: 30000,
      },
    ],
    invoiceId: "inv_901234",
    transactionId: "txn_JKL012",
    description: "Purchase of Product E",
    taxAmount: 2500,
    discountAmount: 0,
    billingAddress: {
      street: "123 Elm St",
      city: "Sydney",
      state: "NSW",
      postalCode: "2000",
      country: "Australia",
    },
  },
  {
    paymentId: "pay_567890",
    customerEmail: "customer5@example.com",
    paymentMethod: "Apple Pay",
    amount: 18000,
    currency: "USD",
    status: "Completed",
    paymentDate: "2024-09-17T09:00:00Z",
    products: [
      {
        productId: "prod_006",
        productName: "Product F",
        quantity: 2,
        unitPrice: 9000,
        totalPrice: 18000,
      },
    ],
    invoiceId: "inv_567890",
    transactionId: "txn_MNO345",
    description: "Purchase of Product F",
    taxAmount: 1600,
    discountAmount: 200,
    billingAddress: {
      street: "456 Maple St",
      city: "San Francisco",
      state: "CA",
      postalCode: "94103",
      country: "USA",
    },
  },
];
