export const products = [
  {
    productName: "Baby Lotion",
    price: 52.23,
    ImageUrl: "https://example.com/images/baby_lotion.jpg",
    categoryName: "baby-care",
    discountPrice: 41.58,
    createdBy: "user_6",
    subCategory: "baby-accessories",
  },
  {
    productName: "Shampoo",
    price: 165.94,
    ImageUrl: "https://example.com/images/shampoo.jpg",
    categoryName: "personal-care",
    discountPrice: 151.66,
    createdBy: "user_7",
    subCategory: "men",
  },
  {
    productName: "Basketball",
    price: 38.4,
    ImageUrl: "https://example.com/images/basketball.jpg",
    categoryName: "toy-sports",
    discountPrice: 33.81,
    createdBy: "user_1",
    subCategory: "sports",
  },
  {
    productName: "Diapers",
    price: 15.48,
    ImageUrl: "https://example.com/images/diapers.jpg",
    categoryName: "baby-care",
    discountPrice: 12.34,
    createdBy: "user_7",
    subCategory: "baby-accessories",
  },
  {
    productName: "Mango",
    price: 65.05,
    ImageUrl: "https://example.com/images/rice.jpg",
    categoryName: "food",
    discountPrice: 55.72,
    createdBy: "user_8",
    subCategory: "fruit-vegetable",
  },
  {
    productName: "Hair Dryer",
    price: 44.41,
    ImageUrl: "https://example.com/images/hair_dryer.jpg",
    categoryName: "personal-care",
    discountPrice: 36.56,
    createdBy: "user_9",
    subCategory: "men",
  },
  {
    productName: "Chocolate",
    price: 180.31,
    ImageUrl: "https://example.com/images/chocolate.jpg",
    categoryName: "food",
    discountPrice: 132.11,
    createdBy: "user_8",
    subCategory: "dairy",
  },
  {
    productName: "Vacuum Cleaner",
    price: 180.85,
    ImageUrl: "https://example.com/images/vacuum_cleaner.jpg",
    categoryName: "home-kitchen",
    discountPrice: 159.35,
    createdBy: "user_8",
    subCategory: "cleaning-items",
  },
  {
    productName: "Bicycle",
    price: 99.91,
    ImageUrl: "https://example.com/images/bicycle.jpg",
    categoryName: "toy-sports",
    discountPrice: 74.03,
    createdBy: "user_4",
    subCategory: "toy",
  },
  {
    productName: "Mixer Grinder",
    price: 101.72,
    ImageUrl: "https://example.com/images/mixer_grinder.jpg",
    categoryName: "home-kitchen",
    discountPrice: 77.55,
    createdBy: "user_7",
    subCategory: "kitchen",
  },
  {
    productName: "Toy Car",
    price: 25.79,
    ImageUrl: "https://example.com/images/toy_car.jpg",
    categoryName: "toy-sports",
    discountPrice: 19.55,
    createdBy: "user_3",
    subCategory: "toy",
  },
  {
    productName: "Hilsa Fish",
    price: 20.14,
    ImageUrl: "https://example.com/images/pasta.jpg",
    categoryName: "food",
    discountPrice: 16.95,
    createdBy: "user_2",
    subCategory: "meat-fish",
  },
  {
    productName: "Action Figure",
    price: 116.05,
    ImageUrl: "https://example.com/images/action_figure.jpg",
    categoryName: "toy-sports",
    discountPrice: 106.54,
    createdBy: "user_9",
    subCategory: "toy",
  },
  {
    productName: "Perfume",
    price: 175.28,
    ImageUrl: "https://example.com/images/perfume.jpg",
    categoryName: "personal-care",
    discountPrice: 140.22,
    createdBy: "user_5",
    subCategory: "women",
  },
  {
    productName: "Toothpaste",
    price: 37.88,
    ImageUrl: "https://example.com/images/toothpaste.jpg",
    categoryName: "personal-care",
    discountPrice: 35.9,
    createdBy: "user_10",
    subCategory: "women",
  },
  {
    productName: "Football",
    price: 134.98,
    ImageUrl: "https://example.com/images/football.jpg",
    categoryName: "toy-sports",
    discountPrice: 117.93,
    createdBy: "user_4",
    subCategory: "sports",
  },
  {
    productName: "Baby Milk",
    price: 159.13,
    ImageUrl: "https://example.com/images/baby_powder.jpg",
    categoryName: "baby-care",
    discountPrice: 123.0,
    createdBy: "user_3",
    subCategory: "baby-food",
  },
  {
    productName: "Beef",
    price: 149.01,
    ImageUrl: "https://example.com/images/cookies.jpg",
    categoryName: "food",
    discountPrice: 105.45,
    createdBy: "user_2",
    subCategory: "meat-fish",
  },
  {
    productName: "Baby Powder",
    price: 104.16,
    ImageUrl: "https://example.com/images/baby_powder.jpg",
    categoryName: "baby-care",
    discountPrice: 83.2,
    createdBy: "user_9",
    subCategory: "baby-accessories",
  },
  {
    productName: "Dining Set",
    price: 98.82,
    ImageUrl: "https://example.com/images/dining_set.jpg",
    categoryName: "home-kitchen",
    discountPrice: 79.23,
    createdBy: "user_5",
    subCategory: "kitchen",
  },
  {
    productName: "Shampoo",
    price: 61.62,
    ImageUrl: "https://example.com/images/shampoo.jpg",
    categoryName: "personal-care",
    discountPrice: 47.86,
    createdBy: "user_4",
    subCategory: "men",
  },
  {
    productName: "Dining Set",
    price: 75.33,
    ImageUrl: "https://example.com/images/dining_set.jpg",
    categoryName: "home-kitchen",
    discountPrice: 66.89,
    createdBy: "user_9",
    subCategory: "household",
  },
  {
    productName: "Hair Dryer",
    price: 161.22,
    ImageUrl: "https://example.com/images/hair_dryer.jpg",
    categoryName: "personal-care",
    discountPrice: 138.8,
    createdBy: "user_6",
    subCategory: "women",
  },
  {
    productName: "Cookies",
    price: 58.47,
    ImageUrl: "https://example.com/images/cookies.jpg",
    categoryName: "food",
    discountPrice: 42.38,
    createdBy: "user_6",
    subCategory: "dairy",
  },
];
