export const products = [
  {
    id: 1,
    productName: "Baby Lotion",
    price: 52.23,
    ImageUrl: "https://i.ibb.co.com/myXN0P5/30.png",
    categoryName: "baby-care",
    discountPrice: 41.58,
    createdBy: "user_6",
    subCategory: "baby-accessories",
  },
  {
    id: 2,
    productName: "Shampoo",
    price: 165.94,
    ImageUrl: "https://i.ibb.co.com/myXN0P5/30.png",
    categoryName: "personal-care",
    discountPrice: 151.66,
    createdBy: "user_7",
    subCategory: "men",
  },
  {
    id: 3,
    productName: "Basketball",
    price: 38.4,
    ImageUrl: "https://i.ibb.co.com/myXN0P5/30.png",
    categoryName: "toy-sports",
    discountPrice: 33.81,
    createdBy: "user_1",
    subCategory: "sports",
  },
  {
    id: 4,
    productName: "Diapers",
    price: 15.48,
    ImageUrl: "https://i.ibb.co.com/myXN0P5/30.png",
    categoryName: "baby-care",
    discountPrice: 12.34,
    createdBy: "user_7",
    subCategory: "baby-accessories",
  },
  {
    id: 5,
    productName: "Mango",
    price: 65.05,
    ImageUrl: "https://i.ibb.co.com/myXN0P5/30.png",
    categoryName: "food",
    discountPrice: 55.72,
    createdBy: "user_8",
    subCategory: "fruit-vegetable",
  },
  {
    id: 6,
    productName: "Hair Dryer",
    price: 44.41,
    ImageUrl: "https://i.ibb.co.com/myXN0P5/30.png",
    categoryName: "personal-care",
    discountPrice: 36.56,
    createdBy: "user_9",
    subCategory: "men",
  },
  {
    id: 7,
    productName: "Chocolate",
    price: 180.31,
    ImageUrl: "https://i.ibb.co.com/myXN0P5/30.png",
    categoryName: "food",
    discountPrice: 132.11,
    createdBy: "user_8",
    subCategory: "dairy",
  },
  {
    id: 8,
    productName: "Vacuum Cleaner",
    price: 180.85,
    ImageUrl: "https://i.ibb.co.com/myXN0P5/30.png",
    categoryName: "home-kitchen",
    discountPrice: 159.35,
    createdBy: "user_8",
    subCategory: "cleaning-items",
  },
  {
    id: 9,
    productName: "Bicycle",
    price: 99.91,
    ImageUrl: "https://i.ibb.co.com/myXN0P5/30.png",
    categoryName: "toy-sports",
    discountPrice: 74.03,
    createdBy: "user_4",
    subCategory: "toy",
  },
  {
    id: 10,
    productName: "Mixer Grinder",
    price: 101.72,
    ImageUrl: "https://i.ibb.co.com/myXN0P5/30.png",
    categoryName: "home-kitchen",
    discountPrice: 77.55,
    createdBy: "user_7",
    subCategory: "kitchen",
  },
  {
    id: 11,
    productName: "Toy Car",
    price: 25.79,
    ImageUrl: "https://i.ibb.co.com/myXN0P5/30.png",
    categoryName: "toy-sports",
    discountPrice: 19.55,
    createdBy: "user_3",
    subCategory: "toy",
  },
  {
    id: 12,
    productName: "Hilsa Fish",
    price: 20.14,
    ImageUrl: "https://i.ibb.co.com/myXN0P5/30.png",
    categoryName: "food",
    discountPrice: 16.95,
    createdBy: "user_2",
    subCategory: "meat-fish",
  },
  {
    id: 13,
    productName: "Action Figure",
    price: 116.05,
    ImageUrl: "https://i.ibb.co.com/myXN0P5/30.png",
    categoryName: "toy-sports",
    discountPrice: 106.54,
    createdBy: "user_9",
    subCategory: "toy",
  },
  {
    id: 14,
    productName: "Perfume",
    price: 175.28,
    ImageUrl: "https://i.ibb.co.com/myXN0P5/30.png",
    categoryName: "personal-care",
    discountPrice: 140.22,
    createdBy: "user_5",
    subCategory: "women",
  },
  {
    id: 15,
    productName: "Toothpaste",
    price: 37.88,
    ImageUrl: "https://i.ibb.co.com/myXN0P5/30.png",
    categoryName: "personal-care",
    discountPrice: 35.9,
    createdBy: "user_10",
    subCategory: "women",
  },
  {
    id: 16,
    productName: "Football",
    price: 134.98,
    ImageUrl: "https://i.ibb.co.com/myXN0P5/30.png",
    categoryName: "toy-sports",
    discountPrice: 117.93,
    createdBy: "user_4",
    subCategory: "sports",
  },
  {
    id: 17,
    productName: "Baby Milk",
    price: 159.13,
    ImageUrl: "https://i.ibb.co.com/myXN0P5/30.png",
    categoryName: "baby-care",
    discountPrice: 123.0,
    createdBy: "user_3",
    subCategory: "baby-food",
  },
  {
    id: 18,
    productName: "Beef",
    price: 149.01,
    ImageUrl: "https://i.ibb.co.com/myXN0P5/30.png",
    categoryName: "food",
    discountPrice: 105.45,
    createdBy: "user_2",
    subCategory: "meat-fish",
  },
  {
    id: 19,
    productName: "Baby Powder",
    price: 104.16,
    ImageUrl: "https://i.ibb.co.com/myXN0P5/30.png",
    categoryName: "baby-care",
    discountPrice: 83.2,
    createdBy: "user_9",
    subCategory: "baby-accessories",
  },
  {
    id: 20,
    productName: "Dining Set",
    price: 98.82,
    ImageUrl: "https://i.ibb.co.com/myXN0P5/30.png",
    categoryName: "home-kitchen",
    discountPrice: 79.23,
    createdBy: "user_5",
    subCategory: "kitchen",
  },
  {
    id: 21,
    productName: "Shampoo",
    price: 61.62,
    ImageUrl: "https://i.ibb.co.com/myXN0P5/30.png",
    categoryName: "personal-care",
    discountPrice: 47.86,
    createdBy: "user_4",
    subCategory: "men",
  },
  {
    id: 22,
    productName: "Dining Set",
    price: 75.33,
    ImageUrl: "https://i.ibb.co.com/myXN0P5/30.png",
    categoryName: "home-kitchen",
    discountPrice: 66.89,
    createdBy: "user_9",
    subCategory: "household",
  },
  {
    id: 23,
    productName: "Hair Dryer",
    price: 161.22,
    ImageUrl: "https://i.ibb.co.com/myXN0P5/30.png",
    categoryName: "personal-care",
    discountPrice: 138.8,
    createdBy: "user_6",
    subCategory: "women",
  },
  {
    id: 24,
    productName: "Cookies",
    price: 58.47,
    ImageUrl: "https://i.ibb.co.com/myXN0P5/30.png",
    categoryName: "food",
    discountPrice: 42.38,
    createdBy: "user_6",
    subCategory: "dairy",
  },
];
